### ISSUE TITLE
Add a link on how to request FB archive

### ISSUE THREAD

**Issue by epogrebnyak** [itzmeanjan/fviz#11]
The text _I'm assuming you requested FB archive file_ can benefit from a link on how to get it.

**Comment by epogrebnyak** [comment]
Maybe this should be this link: https://m.facebook.com/help/212802592074644?helpref=hc_fnav

**Comment by itzmeanjan** [comment]
That's a very correct suggestion @epogrebnyak . Thanks :) 

:clap:

**Comment by itzmeanjan** [comment]
This issue has been resolved. Please check [here](https://github.com/itzmeanjan/fviz#usage). 

Thanks for your contribution :wink:
