### ISSUE TITLE
Replace generic exception

### ISSUE THREAD

**Issue by epogrebnyak** [itzmeanjan/fviz#12]
https://github.com/itzmeanjan/fviz/blob/e52d7fb114db90a5e9b218a824e2422520e1eb89/fviz/extract.py#L18

Having a generic exception in code is not a good feature - is ther eany speciifc error you are protecting against?

**Comment by itzmeanjan** [comment]
It's not required in this certain case, but there're places during plotting _( matplotlib specific issues during exporting image as **jpg** )_, it may be required. So I thought of protecting it from those places, and rather show result of whole operation in terms of [percentage](https://github.com/itzmeanjan/fviz/blob/eee80277b5afff502a8c3db429d563531196727a/fviz/main.py#L226). 

Though you're absolutely correct about generic exception, I'll require to refactor code.
