### ISSUE TITLE
Shebang and annotations

### ISSUE THREAD

**Issue by epogrebnyak** [itzmeanjan/fviz#13]
https://github.com/itzmeanjan/fviz/blob/e52d7fb114db90a5e9b218a824e2422520e1eb89/fviz/extract.py#L1-L3

You might not need those in python 3, do you?

**Comment by itzmeanjan** [comment]
This declaration is required for type annotation done in [code](https://github.com/itzmeanjan/fviz/blob/eee80277b5afff502a8c3db429d563531196727a/fviz/main.py#L41), which was introduced in python 3.7.0. 

```python
def _calculateSuccess(arr: List[bool]) -> float:
    '''
        Calculates percentage of success
    '''
    return (arr.count(True) / len(arr)) * 100
```

**Comment by epogrebnyak** [comment]
No, you can have type annotation without `from __future__ import annotations`, it is perfectly valid in 3.7 and up. 

`from __future__ import annotations` deals with a special case of postponing evaluation, which you may not even have or deal by differently (eg by declarations, where necessary).

**Comment by itzmeanjan** [comment]
Oh I didn't know that, I'll remove them :wink:
