### ISSUE TITLE
can be refactored to dataclass and an extra method/function 

### ISSUE THREAD

**Issue by epogrebnyak** [itzmeanjan/fviz#14]
https://github.com/itzmeanjan/fviz/blob/eee80277b5afff502a8c3db429d563531196727a/fviz/model/friend.py#L7

**Comment by itzmeanjan** [comment]
I've not added any extra method to it as it was not required then. I'll consider doing so, when some requirement comes up.

**Comment by epogrebnyak** [comment]
Something like below: 

```python
@dataclass
class Friend:
  namе: str
  time datetime.datetime
```

**Comment by itzmeanjan** [comment]
Wow, this looks nice. Thanks :relaxed:

**Comment by itzmeanjan** [comment]
Added `dataclass` decorator [here](https://github.com/itzmeanjan/fviz/commit/f0e7b1560250b8dfb1749639e1d1f8fd191380ce).
